services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ochorocho\LitDemo\:
    resource: '../Classes/*'

  Ochorocho\LitDemo\Security\ApiCspProvider:
    tags:
      - name: csp.policy-provider
        identifier: 'lit-demo/csp-provider'